package com.secbro2;

//import com.secbro2.entity.Person;
unit PersonUnit;

// 规则1：小于18岁
rule "less-than-18-years-old"
when
//    $p : Person(age < 18);
    $p : /persons[age < 18];
then
    $p.setScore(0);
    $p.setDesc("年龄不符合条件");
end

// 规则2：18到30岁
rule "between-18-and-30-years-old"
when
//    $p : Person(age >= 18,age < 30);
    $p : /persons[age >= 18,age < 30];
then
    $p.setScore($p.getScore() + 60);
end

// 规则3：30到65岁
rule "between-30-and-65-years-old"
when
//    $p : Person(age >= 30,age < 65);
    $p : /persons[age >= 30,age < 65];
then
    $p.setScore($p.getScore() + 80);
end

// 规则4：65岁以上
rule "greater-than-65-years-old"
when
//    $p : Person(age >= 65);
    $p : /persons[age >= 65];
then
    $p.setScore($p.getScore() + 40);
end

query "between-18-and-65-years-old"
// $p : Person(age >= 18,age < 65);
   $p : /persons[age >= 18,age < 65];
end
